# Generated by Django 2.1.12 on 2020-03-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticles',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.RenameField(
            model_name='blogarticles',
            old_name='publish',
            new_name='publish_date',
        ),
    ]
